name: Create Sprint milestone every 2 weeks on wednesday

on:
  schedule:
    # Run script on every wednesday at midnight
    - cron: '0 0 * * WED'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get week number
        # Check if current week number is odd, for running automation every 2 weeks
        run: echo "ODD_WEEK=$(expr $(date +%U) % 2)" >> $GITHUB_ENV
        
      - name: Sprint Milestone Action
        # Runs on odd week numbers (so ODD_WEEK = 1)
        if: env.ODD_WEEK == 1
        run: |
          dueDate=$(date -d "2 weeks" +"%Y-%m-%d") \
          && \
          lastSprintNumber=$(curl \
          -H "Accept: application/vnd.github.v3+json" \
          -u n1c01a5:${{ secrets.GHPROJECT_TOKEN }} \
          https://api.github.com/repos/feature-sh/app/milestones \
          | grep "Sprint" | grep -o -E "[0-9]+" | sort -n | tail -1) \
          && \
          newSprintNumber=$(expr $lastSprintNumber + 1) \
          && \
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -u n1c01a5:${{ secrets.GHPROJECT_TOKEN }} \
          https://api.github.com/repos/$GITHUB_REPOSITORY/milestones \
          -d '{"title":"Sprint '"${newSprintNumber}"'","state":"open","description":"","due_on":"'"${dueDate}"'T00:00:00Z"}'
