name: Projects CI

on:
  issues: 
    types: [opened, reopened]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so jobs can access it
      - uses: actions/checkout@v3

      # Automatically add issues and PRs to GitHub projects beta
      - name: Add To GitHub Projects Beta
        uses: actions/add-to-project@v0.0.3
        with:
          # URL of the project to add issues to
          project-url: https://github.com/orgs/feature-sh/projects/1
          # A GitHub personal access token with write access to the project
          github-token: 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
